### ISSUE TITLE
Failed to load config "@pvtnbr" to extend from

### ISSUE THREAD

**Issue by alexmccabe** [privatenumber/vue-frag#65]
Getting this error during the `vite build` command all of a sudden. I've cleared `node_module` and `yarn.lock` and it's still happening

```
[vite-plugin-eslint] Failed to load config "@pvtnbr" to extend from.
Referenced from: /Users/alexmccabe/Sites/ui-library/node_modules/vue-frag/package.json
file: /Users/alexmccabe/Sites/ui-library/node_modules/vue-frag/dist/frag.esm.js
error during build:
Error: Failed to load config "@pvtnbr" to extend from.
Referenced from: /Users/alexmccabe/Sites/ui-library/node_modules/vue-frag/package.json
    at configInvalidError (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/alexmccabe/Sites/ui-library/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alexmccabe** [comment]
Turns out that this is a `vite-plugin-eslint` issue

https://github.com/gxmari007/vite-plugin-eslint/issues/38

**Comment by privatenumber** [comment]
FWIW I published a version that removes any development related code from `package.json`: https://unpkg.com/vue-frag@1.4.1/package.json

**Comment by alexmccabe** [comment]
@privatenumber nice work. Will get updated to latest, thank you
